services:
  - type: web
    name: lovable-clone
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLAUDE_API_KEY_1
        sync: false  # Set this manually in Render dashboard
      - key: ANTHROPIC_API_KEY
        sync: false  # Set this manually in Render dashboard